import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { auth } from "@/auth";

const inter = Inter({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  console.log(session?.user)

  return (
    <html lang="en">
      <body className={cn(inter.className, 'antialiased')}>
        <main className="flex flex-col min-h-[100dvh]">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
